services:
  - type: web
    name: terra-roxa-system
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn run:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_APP
        value: run.py
      - key: DATABASE_URL
        fromDatabase:
          name: terra-roxa-db
          property: connectionString
    healthCheckPath: /login

databases:
  - name: terra-roxa-db
    databaseName: gadoleiteiro
    user: admin
    plan: free
