"""Onda2: indices, campos gordura/proteina/ccs, telefone/email/endereco, tipo_racao, reproducao

Revision ID: 9e6484053666
Revises: 
Create Date: 2026-06-23 20:14:21.765942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e6484053666'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('consumo_racao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consumo_racao_animal_id'), ['animal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consumo_racao_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_consumo_racao_tipo_racao_id'), ['tipo_racao_id'], unique=False)

    with op.batch_alter_table('despesa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_despesa_categoria'), ['categoria'], unique=False)
        batch_op.create_index(batch_op.f('ix_despesa_data'), ['data'], unique=False)

    with op.batch_alter_table('preco_leite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_preco_leite_data_vigencia'), ['data_vigencia'], unique=False)

    with op.batch_alter_table('producao_leite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_producao_leite_animal_id'), ['animal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_producao_leite_data'), ['data'], unique=False)

    with op.batch_alter_table('saude_animal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saude_animal_animal_id'), ['animal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saude_animal_proxima_dose'), ['proxima_dose'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_ativo'), ['ativo'], unique=False)

    with op.batch_alter_table('venda_avulsa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_venda_avulsa_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_venda_avulsa_data'), ['data'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda_avulsa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_venda_avulsa_data'))
        batch_op.drop_index(batch_op.f('ix_venda_avulsa_cliente_id'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_ativo'))

    with op.batch_alter_table('saude_animal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saude_animal_proxima_dose'))
        batch_op.drop_index(batch_op.f('ix_saude_animal_animal_id'))

    with op.batch_alter_table('producao_leite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_producao_leite_data'))
        batch_op.drop_index(batch_op.f('ix_producao_leite_animal_id'))

    with op.batch_alter_table('preco_leite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_preco_leite_data_vigencia'))

    with op.batch_alter_table('despesa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_despesa_data'))
        batch_op.drop_index(batch_op.f('ix_despesa_categoria'))

    with op.batch_alter_table('consumo_racao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consumo_racao_tipo_racao_id'))
        batch_op.drop_index(batch_op.f('ix_consumo_racao_data'))
        batch_op.drop_index(batch_op.f('ix_consumo_racao_animal_id'))

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_timestamp'))

    # ### end Alembic commands ###
